version: '3.8'

services:
  fast_app:
    container_name: fast_app
    build:
      context: .
    command: sh -c "ls"
    volumes:
      - .:/code/app
    depends_on:
      - db
    links:
      - db
#    networks:
#      - postgres

  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#      - .:/var/lib/postgresql/data
#    networks:
#      - postgres
#
#networks:
#  postgres:
#    driver: bridge
