version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    command: sh -c "uvicorn app.main:app --reload --proxy-headers --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
#    volumes:
#      - .:/docker-entrypoint-initdb.d
#      - db-data:/var/lib/postgresql/data
#
#volumes:
#  db-data:

networks:
  backend:

