version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
    command: sh -c "uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres:13-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  db-data:
    driver: local

networks:
  postgres:
    driver: bridge
